  steps:
    - uses: actions/checkout@v2 # <-- must be provided, else no source repo is provided to anonymized-mirror-action
      with:
        fetch-depth: "0" # <-- must be 0 to prevent shallow clone issues
        ref: "main" # <-- the branch you want to get mirrored and anonymized
    - uses: pstnorge/anonymized-mirror-action@main
      with:
        ssh_private_key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }} # <-- use GitHub secrets for the SSH key
        destination_git_url: "git@github.com:pstnorge/public-anonymized-repo.git"
        mirror_branch: "mirror"
        anon_name: "PST"
        anon_email: "noreply@pst.no"
